# Generated by Django 5.0 on 2025-05-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_stats_entry_stats_invoice_count_stats_invoice_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='invoice_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='invoice_item',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
