# Generated by Django 5.0 on 2025-05-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_stats_invoice_count_alter_stats_invoice_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="branch",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stats",
            name="vendor",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
