# Generated by Django 5.0 on 2025-05-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_stats_branch_stats_vendor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stats",
            options={"verbose_name": "شمارشگر", "verbose_name_plural": "شمارشگر"},
        ),
        migrations.AlterField(
            model_name="stats",
            name="branch",
            field=models.CharField(max_length=255, null=True, verbose_name="شعبه"),
        ),
        migrations.AlterField(
            model_name="stats",
            name="date",
            field=models.DateField(verbose_name="تاریخ"),
        ),
        migrations.AlterField(
            model_name="stats",
            name="entry",
            field=models.IntegerField(default=0, verbose_name="ورودی"),
        ),
        migrations.AlterField(
            model_name="stats",
            name="invoice_count",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="تعداد فاکتور"
            ),
        ),
        migrations.AlterField(
            model_name="stats",
            name="invoice_item",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="آیتم فاکتور"
            ),
        ),
        migrations.AlterField(
            model_name="stats",
            name="vendor",
            field=models.CharField(max_length=255, null=True, verbose_name="فروشگاه"),
        ),
    ]
