# Generated by Django 5.0 on 2025-05-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_stats_options_alter_stats_branch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام کمپین")),
                ("date", models.DateField(verbose_name="تاریخ")),
            ],
            options={
                "verbose_name": "کمپین",
                "verbose_name_plural": "کمپین",
            },
        ),
        migrations.CreateModel(
            name="DefaultDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateField(verbose_name="تاریخ پایان")),
            ],
            options={
                "verbose_name": "تاریخ پیش فرض",
                "verbose_name_plural": "تاریخ پیش فرض",
            },
        ),
    ]
