# Generated by Django 5.0 on 2025-05-28 14:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_campaign_defaultdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 5, 28, 18, 2, 10, 949230),
                        null=True,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone", models.CharField(max_length=255)),
                ("entry", models.CharField(max_length=255)),
                ("ip", models.CharField(max_length=255)),
                ("cam_name", models.CharField(max_length=255)),
                ("google_longitude", models.CharField(max_length=255)),
                ("google_latitude", models.CharField(max_length=255)),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 5, 28, 18, 2, 10, 949731),
                        null=True,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام کمپین")),
                ("start_date", models.DateField(verbose_name="تاریخ")),
                ("end_date", models.DateField()),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 5, 28, 18, 2, 10, 950841),
                        null=True,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "کمپین",
                "verbose_name_plural": "کمپین",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 5, 28, 18, 2, 10, 948516),
                        null=True,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 5, 28, 18, 2, 10, 947806),
                        null=True,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 5, 28, 18, 2, 10, 948862),
                        null=True,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.city"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rep_first_name", models.CharField(max_length=255)),
                ("rep_last_name", models.CharField(max_length=255)),
                ("rep_mobile_number", models.CharField(max_length=11)),
                ("contract_start_date", models.DateField()),
                ("contract_expiration_date", models.DateField()),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 5, 28, 18, 2, 10, 947193),
                        null=True,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PeopleCounting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("entry", models.IntegerField(default=0, verbose_name="ورودی")),
                ("exit", models.IntegerField(default=0, verbose_name="خروجی")),
                (
                    "vendor",
                    models.CharField(max_length=255, null=True, verbose_name="فروشگاه"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 5, 28, 18, 2, 10, 950296),
                        null=True,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "شمارشگر",
                "verbose_name_plural": "شمارشگر",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 5, 28, 18, 2, 10, 948140),
                        null=True,
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.country",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Campaign",
        ),
        migrations.DeleteModel(
            name="stats",
        ),
        migrations.AddField(
            model_name="defaultdate",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 28, 18, 2, 10, 951203), null=True
            ),
        ),
        migrations.AddField(
            model_name="defaultdate",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cam",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.city"
            ),
        ),
        migrations.AddField(
            model_name="cam",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.country"
            ),
        ),
        migrations.AddField(
            model_name="cam",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.district"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.district"
            ),
        ),
        migrations.AddField(
            model_name="cam",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.merchant"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.merchant"
            ),
        ),
        migrations.AddField(
            model_name="peoplecounting",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.branch",
                verbose_name="شعبه",
            ),
        ),
        migrations.AddField(
            model_name="peoplecounting",
            name="cam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.cam"
            ),
        ),
        migrations.AddField(
            model_name="peoplecounting",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.merchant"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.province"
            ),
        ),
        migrations.AddField(
            model_name="cam",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.province"
            ),
        ),
    ]
