# Generated by Django 5.0 on 2025-05-28 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0007_branch_cam_campaigncalendar_city_country_district_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="peoplecounting",
            name="vendor",
        ),
        migrations.AlterField(
            model_name="branch",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 28, 20, 31, 28, 901207), null=True
            ),
        ),
        migrations.AlterField(
            model_name="cam",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 28, 20, 31, 28, 901711), null=True
            ),
        ),
        migrations.AlterField(
            model_name="campaigncalendar",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 28, 20, 31, 28, 902886), null=True
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 28, 20, 31, 28, 900404), null=True
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 28, 20, 31, 28, 899758), null=True
            ),
        ),
        migrations.AlterField(
            model_name="defaultdate",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 28, 20, 31, 28, 903252), null=True
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 28, 20, 31, 28, 900849), null=True
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 28, 20, 31, 28, 899419), null=True
            ),
        ),
        migrations.AlterField(
            model_name="peoplecounting",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 28, 20, 31, 28, 902282), null=True
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 5, 28, 20, 31, 28, 900054), null=True
            ),
        ),
    ]
