# Generated by Django 5.0 on 2025-05-31 13:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_defaultdate_user_alter_branch_date_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name": "شعبه", "verbose_name_plural": "شعبه"},
        ),
        migrations.AlterModelOptions(
            name="cam",
            options={"verbose_name": "کشور", "verbose_name_plural": "کشور"},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "شهر", "verbose_name_plural": "شهر"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "کشور", "verbose_name_plural": "کشور"},
        ),
        migrations.AlterModelOptions(
            name="district",
            options={"verbose_name": "منطقه", "verbose_name_plural": "منطقه"},
        ),
        migrations.AlterModelOptions(
            name="merchant",
            options={"verbose_name": "مرچنت", "verbose_name_plural": "مرچنت"},
        ),
        migrations.AlterModelOptions(
            name="province",
            options={"verbose_name": "استان", "verbose_name_plural": "استان"},
        ),
        migrations.AlterField(
            model_name="branch",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime.now, null=True, verbose_name="تاریخ ساخت"
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.district",
                verbose_name="منطقه",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ آخرین تغییر"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.merchant",
                verbose_name="مرچنت",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=255, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="cam",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.branch",
                verbose_name="شعبه",
            ),
        ),
        migrations.AlterField(
            model_name="cam",
            name="cam_name",
            field=models.CharField(max_length=255, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="cam",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.city",
                verbose_name="شهر",
            ),
        ),
        migrations.AlterField(
            model_name="cam",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.country",
                verbose_name="کشور",
            ),
        ),
        migrations.AlterField(
            model_name="cam",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime.now, null=True, verbose_name="تاریخ ساخت"
            ),
        ),
        migrations.AlterField(
            model_name="cam",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.district",
                verbose_name="منطقه",
            ),
        ),
        migrations.AlterField(
            model_name="cam",
            name="entry",
            field=models.CharField(max_length=255, verbose_name="ورودی"),
        ),
        migrations.AlterField(
            model_name="cam",
            name="google_latitude",
            field=models.CharField(max_length=255, verbose_name="Google Longitude"),
        ),
        migrations.AlterField(
            model_name="cam",
            name="google_longitude",
            field=models.CharField(max_length=255, verbose_name="Google Latitude"),
        ),
        migrations.AlterField(
            model_name="cam",
            name="ip",
            field=models.CharField(max_length=255, verbose_name="IP"),
        ),
        migrations.AlterField(
            model_name="cam",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ آخرین تغییر"),
        ),
        migrations.AlterField(
            model_name="cam",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.merchant",
                verbose_name="مرچنت",
            ),
        ),
        migrations.AlterField(
            model_name="cam",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.province",
                verbose_name="استان",
            ),
        ),
        migrations.AlterField(
            model_name="cam",
            name="zone",
            field=models.CharField(max_length=255, verbose_name="زون"),
        ),
        migrations.AlterField(
            model_name="campaigncalendar",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.branch",
                verbose_name="شعبه",
            ),
        ),
        migrations.AlterField(
            model_name="campaigncalendar",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime.now, null=True, verbose_name="تاریخ ساخت"
            ),
        ),
        migrations.AlterField(
            model_name="campaigncalendar",
            name="end_date",
            field=models.DateField(verbose_name="تاریخ پایان"),
        ),
        migrations.AlterField(
            model_name="campaigncalendar",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ آخرین تغییر"),
        ),
        migrations.AlterField(
            model_name="city",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime.now, null=True, verbose_name="تاریخ ساخت"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ آخرین تغییر"),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=255, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="city",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.province",
                verbose_name="استان",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime.now, null=True, verbose_name="تاریخ ساخت"
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ آخرین تغییر"),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=255, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="defaultdate",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime.now, null=True, verbose_name="تاریخ ساخت"
            ),
        ),
        migrations.AlterField(
            model_name="defaultdate",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ آخرین تغییر"),
        ),
        migrations.AlterField(
            model_name="defaultdate",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.city",
                verbose_name="شهر",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime.now, null=True, verbose_name="تاریخ ساخت"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ آخرین تغییر"),
        ),
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(max_length=255, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="contract_expiration_date",
            field=models.DateField(verbose_name="تاریخ انقضای قرارداد"),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="contract_start_date",
            field=models.DateField(verbose_name="تاریخ شروع قرارداد"),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime.now, null=True, verbose_name="تاریخ ساخت"
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ آخرین تغییر"),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="name",
            field=models.CharField(max_length=255, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="rep_first_name",
            field=models.CharField(max_length=255, verbose_name="نام نماینده"),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="rep_last_name",
            field=models.CharField(max_length=255, verbose_name="نام خانوادگی نماینده"),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="rep_mobile_number",
            field=models.CharField(max_length=11, verbose_name="شماره موبایل نماینده"),
        ),
        migrations.AlterField(
            model_name="peoplecounting",
            name="cam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.cam",
                verbose_name="دوربین",
            ),
        ),
        migrations.AlterField(
            model_name="peoplecounting",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime.now, null=True, verbose_name="تاریخ ساخت"
            ),
        ),
        migrations.AlterField(
            model_name="peoplecounting",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ آخرین تغییر"),
        ),
        migrations.AlterField(
            model_name="peoplecounting",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.merchant",
                verbose_name="مرچنت",
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.country",
                verbose_name="کشور",
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime.now, null=True, verbose_name="تاریخ ساخت"
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="last_modified",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ آخرین تغییر"),
        ),
        migrations.AlterField(
            model_name="province",
            name="name",
            field=models.CharField(max_length=255, verbose_name="نام"),
        ),
    ]
