# Generated by Django 5.0 on 2025-05-31 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_alter_branch_options_alter_cam_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cam",
            options={"verbose_name": "دوربین", "verbose_name_plural": "دوربین"},
        ),
        migrations.AlterField(
            model_name="peoplecounting",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people_counts",
                to="dashboard.branch",
                verbose_name="شعبه",
            ),
        ),
        migrations.AlterField(
            model_name="peoplecounting",
            name="cam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people_counts",
                to="dashboard.cam",
                verbose_name="دوربین",
            ),
        ),
        migrations.AlterField(
            model_name="peoplecounting",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people_counts",
                to="dashboard.merchant",
                verbose_name="مرچنت",
            ),
        ),
    ]
