# Generated by Django 5.0 on 2025-05-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_alter_cam_options_alter_peoplecounting_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="url_hash",
            field=models.CharField(max_length=25, null=True, verbose_name="نامک"),
        ),
    ]
