# Generated by Django 5.0 on 2025-06-03 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "نمای کاربر", "verbose_name_plural": "نمای کاربر"},
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="مدیر"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="شماره تلفن"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="dashboard.merchant",
                verbose_name="مرچنت",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
