# Generated by Django 5.0 on 2025-06-07 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_permissiontoviewbranch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissiontoviewbranch",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissiontoviewbranch",
                to="dashboard.userprofile",
                verbose_name="کاربر",
            ),
        ),
    ]
