# Generated by Django 5.0 on 2025-06-08 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_alter_permissiontoviewbranch_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.city",
                verbose_name="شهر",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.country",
                verbose_name="کشور",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.province",
                verbose_name="استان",
            ),
        ),
        migrations.AddField(
            model_name="campaigncalendar",
            name="cost",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="هزینه"
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.district",
                verbose_name="منطقه",
            ),
        ),
    ]
