# Generated by Django 5.0 on 2025-06-08 09:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_branch_city_branch_country_branch_province_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "total_amount",
                    models.CharField(max_length=255, verbose_name="مبلغ کل"),
                ),
                (
                    "total_items",
                    models.CharField(max_length=255, verbose_name="تعداد آیتم"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="تاریخ ساخت",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین تغییر"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاکتور",
                "verbose_name_plural": "فاکتور",
            },
        ),
    ]
