# Generated by Django 5.0 on 2025-06-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="url_hash",
            field=models.CharField(
                db_index=True, max_length=25, null=True, verbose_name="نامک"
            ),
        ),
        migrations.AlterField(
            model_name="peoplecounting",
            name="date",
            field=models.DateField(db_index=True, verbose_name="تاریخ"),
        ),
    ]
