# Generated by Django 5.0 on 2025-06-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0020_alter_branch_name_alter_merchant_url_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="url_hash",
            field=models.CharField(
                db_index=True,
                max_length=25,
                null=True,
                unique=True,
                verbose_name="نامک",
            ),
        ),
    ]
