# Generated by Django 5.0 on 2025-06-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_alter_merchant_url_hash"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DefaultDate",
        ),
    ]
