# Generated by Django 5.0 on 2025-06-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_delete_defaultdate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CampaignCalendar",
            new_name="Campaign",
        ),
    ]
