# Generated by Django 5.0 on 2025-07-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0023_rename_campaigncalendar_campaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_manager",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="مدیر"
            ),
        ),
    ]
