# Generated by Django 5.0 on 2025-08-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_alter_userprofile_is_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="campaign_type",
            field=models.CharField(
                blank=True,
                choices=[("ویترین", "ویترین"), ("فروش", "فروش")],
                max_length=10,
                null=True,
                verbose_name="نوع کمپین",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ پایان"),
        ),
    ]
