# Generated by Django 5.0 on 2025-08-10 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0025_campaign_campaign_type_alter_campaign_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignSpecialId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("special_id", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="special_campaign_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.campaignspecialid",
                verbose_name="کد ویژه کمپین",
            ),
        ),
    ]
