# Generated by Django 5.0 on 2025-08-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0026_campaignspecialid_campaign_special_campaign_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignspecialid",
            options={
                "verbose_name": "کد ویژه کمپین ها",
                "verbose_name_plural": "کد ویژه کمپین ها",
            },
        ),
        migrations.AlterField(
            model_name="campaignspecialid",
            name="special_id",
            field=models.IntegerField(verbose_name="کد ویزه کمپین"),
        ),
    ]
