# Generated by Django 5.0 on 2025-08-10 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_alter_campaignspecialid_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignspecialid",
            name="merchant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.merchant",
                verbose_name="مرچنت",
            ),
        ),
    ]
