# Generated by Django 5.0 on 2025-08-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_campaignspecialid_merchant"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignspecialid",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="نام"
            ),
        ),
    ]
