# Generated by Django 5.0 on 2025-08-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_campaignspecialid_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="special_campaign_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="special",
                to="dashboard.campaignspecialid",
                verbose_name="کد ویژه کمپین",
            ),
        ),
    ]
