# Generated by Django 5.0 on 2025-08-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0030_alter_campaign_special_campaign_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="special_campaign_id",
        ),
        migrations.DeleteModel(
            name="CampaignSpecialId",
        ),
    ]
