# Generated by Django 5.0 on 2025-08-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0031_remove_campaign_special_campaign_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="group_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
