# Generated by Django 5.0 on 2025-08-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0032_campaign_group_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="group_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
