# Generated by Django 5.0 on 2025-08-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0033_alter_campaign_group_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="peoplecounting",
            index=models.Index(
                fields=["merchant", "date"], name="dashboard_p_merchan_62936b_idx"
            ),
        ),
    ]
