# Generated by Django 5.0 on 2025-08-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0034_peoplecounting_dashboard_p_merchan_62936b_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="end_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="تاریخ پایان"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="group_id",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateField(db_index=True, verbose_name="تاریخ"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="date",
            field=models.DateField(db_index=True, verbose_name="تاریخ"),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["branch", "start_date", "end_date"],
                name="dashboard_c_branch__041b9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["branch", "date"], name="dashboard_i_branch__ed588c_idx"
            ),
        ),
    ]
