# Generated by Django 5.0 on 2025-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0035_alter_campaign_end_date_alter_campaign_group_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.IntegerField(verbose_name="مبلغ کل"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_items",
            field=models.IntegerField(verbose_name="تعداد آیتم"),
        ),
    ]
