# Generated by Django 5.0 on 2025-08-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0036_alter_invoice_total_amount_alter_invoice_total_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.BigIntegerField(verbose_name="مبلغ کل"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_items",
            field=models.BigIntegerField(verbose_name="تعداد آیتم"),
        ),
    ]
