# Generated by Django 5.0 on 2025-09-07 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0037_alter_invoice_total_amount_alter_invoice_total_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="HolidayDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(db_index=True, max_length=10)),
            ],
            options={
                "verbose_name": "تاریخ تعطیلات",
                "verbose_name_plural": "تاریخ تعطیلات",
            },
        ),
        migrations.CreateModel(
            name="HolidayDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.holidaydate",
                    ),
                ),
            ],
            options={
                "verbose_name": "مناسبت تعطیلات",
                "verbose_name_plural": "مناسبت تعطیلات",
                "indexes": [
                    models.Index(fields=["date"], name="dashboard_h_date_id_ebb87e_idx")
                ],
            },
        ),
    ]
