# Generated by Django 5.0 on 2025-09-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0038_holidaydate_holidaydescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="holidaydate",
            name="gregorian_date",
            field=models.DateField(null=True),
        ),
    ]
