# Generated by Django 5.0 on 2025-09-07 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0039_holidaydate_gregorian_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holidaydescription",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidaydsc",
                to="dashboard.holidaydate",
            ),
        ),
    ]
