# Generated by Django 5.0 on 2025-09-15 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0040_alter_holidaydescription_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cam",
            name="status",
            field=models.BooleanField(blank=True, null=True, verbose_name="وضعیت"),
        ),
        migrations.AlterField(
            model_name="holidaydate",
            name="date",
            field=models.CharField(max_length=10, verbose_name="تاریخ شمسی"),
        ),
        migrations.AlterField(
            model_name="holidaydate",
            name="gregorian_date",
            field=models.DateField(
                db_index=True, null=True, verbose_name="تاریخ میلادی"
            ),
        ),
        migrations.AlterField(
            model_name="holidaydescription",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidaydsc",
                to="dashboard.holidaydate",
                verbose_name="تاریخ",
            ),
        ),
        migrations.AlterField(
            model_name="holidaydescription",
            name="description",
            field=models.CharField(max_length=255, verbose_name="مناسبت"),
        ),
    ]
