# Generated by Django 5.0 on 2025-09-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0041_cam_status_alter_holidaydate_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="total_product",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="تعداد محصول"
            ),
        ),
    ]
