# Generated by Django 5.0 on 2025-10-18 12:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0042_invoice_total_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertCameraMalfunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "mobile",
                    models.CharField(max_length=11, verbose_name="شماره موبایل"),
                ),
                ("message", models.TextField(verbose_name="متن پیام")),
                ("is_active", models.BooleanField(verbose_name="فعال")),
                ("time_sent", models.TimeField(verbose_name="زمان ارسال")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="تاریخ ساخت",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین تغییر"
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.merchant",
                        verbose_name="مرچنت",
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاع رسانی خطا در سیستم",
                "verbose_name_plural": "اطلاع رسانی خطا در سیستم",
            },
        ),
    ]
