# Generated by Django 5.0 on 2025-10-18 13:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0043_alertcameramalfunction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alertcameramalfunction",
            name="time_sent",
        ),
        migrations.AddField(
            model_name="alertcameramalfunction",
            name="last_time_sent",
            field=models.TimeField(null=True, verbose_name="آخرین زمان ارسال"),
        ),
        migrations.CreateModel(
            name="AlertCameraMalfunctionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="متن پیام")),
                ("time_sent", models.TimeField(verbose_name="آخرین زمان ارسال")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="تاریخ ساخت",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین تغییر"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.alertcameramalfunction",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام خطای اطلاع رسانی دوربین",
                "verbose_name_plural": "پیام خطای اطلاع رسانی دوربین",
            },
        ),
    ]
