# Generated by Django 5.0 on 2025-10-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0044_remove_alertcameramalfunction_time_sent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alertcameramalfunction",
            name="message",
        ),
    ]
