# Generated by Django 5.0 on 2025-10-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0045_remove_alertcameramalfunction_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alertcameramalfunctionmessage",
            name="time_sent",
        ),
        migrations.AlterField(
            model_name="alertcameramalfunction",
            name="last_time_sent",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="آخرین زمان ارسال"
            ),
        ),
    ]
