# Generated by Django 5.0 on 2025-10-18 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0046_remove_alertcameramalfunctionmessage_time_sent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertcameramalfunction",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.merchant",
                verbose_name="مرچنت",
            ),
        ),
    ]
