# Generated by Django 5.0 on 2025-10-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0047_alter_alertcameramalfunction_merchant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertcameramalfunction",
            name="mobile",
            field=models.CharField(
                max_length=11, unique=True, verbose_name="شماره موبایل"
            ),
        ),
    ]
