# Generated by Django 5.0 on 2025-10-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0048_alter_alertcameramalfunction_mobile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alertcameramalfunction",
            options={
                "verbose_name": "مخاطب دریافت پیامک",
                "verbose_name_plural": "مخاطب دریافت پیامک",
            },
        ),
        migrations.AlterField(
            model_name="alertcameramalfunction",
            name="last_time_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="آخرین زمان ارسال"
            ),
        ),
    ]
