# Generated by Django 5.0 on 2025-10-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0049_alter_alertcameramalfunction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name="نام"
            ),
        ),
    ]
