# Generated by Django 5.0 on 2025-11-09 16:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0050_alter_branch_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeopleCountingHourly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("hour", models.TimeField(verbose_name="ساعت")),
                ("entry", models.IntegerField(verbose_name="ورود")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="تاریخ ساخت",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین تغییر"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.branch",
                        verbose_name="شعبه",
                    ),
                ),
                (
                    "cam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.cam",
                        verbose_name="دوربین",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.merchant",
                        verbose_name="مرچنت",
                    ),
                ),
            ],
        ),
    ]
