# Generated by Django 5.0 on 2025-11-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0051_peoplecountinghourly"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="peoplecountinghourly",
            options={
                "verbose_name": "شمارشگر ساعتی",
                "verbose_name_plural": "شمارشگر ساعتی",
            },
        ),
    ]
