# Generated by Django 5.0 on 2025-12-02 06:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0052_alter_peoplecountinghourly_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("invoice_amount", models.IntegerField(verbose_name="فروش")),
                ("invoice_count", models.IntegerField(verbose_name="تعداد فاکتور")),
                ("product_count", models.IntegerField(verbose_name="تعداد محصول")),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="تاریخ ساخت",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین تغییر"
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.merchant",
                        verbose_name="مرچنت",
                    ),
                ),
            ],
            options={
                "verbose_name": "فروش سایت",
                "verbose_name_plural": "فروش سایت",
            },
        ),
        migrations.CreateModel(
            name="WebsiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("unique_visitors", models.IntegerField(verbose_name="ورودی")),
                (
                    "visits",
                    models.IntegerField(blank=True, null=True, verbose_name="بازدید"),
                ),
                (
                    "bounce_rate",
                    models.IntegerField(blank=True, null=True, verbose_name="نرخ پرش"),
                ),
                (
                    "actions_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="تعداد فعالیت"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime.now,
                        null=True,
                        verbose_name="تاریخ ساخت",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ آخرین تغییر"
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.merchant",
                        verbose_name="مرچنت",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویزیت سایت",
                "verbose_name_plural": "ویزیت سایت",
            },
        ),
    ]
