# Generated by Django 5.0 on 2025-12-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0053_websitesales_websitevisit"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitevisit",
            name="time_spent",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="زمان فعال در سایت"
            ),
        ),
    ]
