# Generated by Django 5.0 on 2025-12-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0054_websitevisit_time_spent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="websitevisit",
            name="time_spent",
        ),
        migrations.AddField(
            model_name="websitevisit",
            name="actions_per_visit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="میانگین اکشن در هر بازدید",
            ),
        ),
        migrations.AddField(
            model_name="websitevisit",
            name="avg_time_spent",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="میانگین زمان"
            ),
        ),
        migrations.AddField(
            model_name="websitevisit",
            name="sum_time_spent",
            field=models.IntegerField(blank=True, null=True, verbose_name="مجموع زمان"),
        ),
    ]
