# Generated by Django 5.0 on 2025-12-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0055_remove_websitevisit_time_spent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitesales",
            name="invoice_amount",
            field=models.BigIntegerField(verbose_name="فروش"),
        ),
    ]
